;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
inhook 7 
tuck - f3 7 
tuck - f1 7 
tuck + f0 7 
tuck + f2 7 
knit - f3 7 
knit - f2 7 
knit - f1 7 
knit - f0 7 
releasehook 7 
xfer f0 b0 
xfer f1 bs1 
xfer f2 b2 
xfer f3 bs3 
xfer b0 fs0 
xfer bs1 f1 
xfer b2 fs2 
xfer bs3 f3 
xfer fs0 b0 
xfer fs2 b2 
knit + b0 7 
knit + b2 7 
knit - f3 7 
knit - f1 7 
knit + b0 7 
knit + b2 7 
knit - f3 7 
knit - f1 7 
outhook 7 
drop b0 
drop b2 
drop f3 
drop f1 
